name: readsdnaberts
channels:
  - bioconda
dependencies:
  - python=3.9
  - einops
  - peft
  - omegaconf
  - evaluate
  - accelerate
  - numpy
  - scikit-learn
  - Pillow
  - scipy
  - gdown
  - insilicoseq
  - badread
  - pip
  - pip:
    - textblob==0.17.1
    - textaugment
    - torch
    - transformers==4.27
