name: env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - nextflow
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - biopython
  - insilicoseq
  - badread
  - tqdm
  - python-dotenv
  - pip:
      - torch
      - transformers==4.27
