name: env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - nextflow
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - biopython
  - insilicoseq
  - badread
  - tqdm
  - python-dotenv
  - einops
  - pip:
      - triton==2.0.0.dev20221202
      - torch==1.13.1
      - transformers==4.27
