import matplotlib.pyplot as plt
import argparse
import numpy as np
import pandas as pd
import matplotlib.axes as x
import matplotlib.gridspec as gridspec

def nr_rows_cols(nr_plots):
    n_cols = int(np.ceil(np.sqrt(nr_plots)))
    rows_violin = int(np.ceil(nr_plots/n_cols))
    if n_cols < 4:
        n_rows = rows_violin +4
    else:
        n_rows = rows_violin + 2
    return n_rows,rows_violin,n_cols

def try_gs_vis(file1,file2,dataframe_list,rows,rows_violin,cols,save_distance_visualization):
    gs_vio = gridspec.GridSpec(rows_violin,cols,left=0.05,right=0.95,top=0.95,bottom=0.4,wspace=0.4,hspace=0.2)
    labels_set=list(set(file2['true_label']))
    cur_row=0
    fig = plt.figure(figsize=(cols*4, rows*3))  
    ax_vio_tit = fig.add_axes((0.05,0.95,1,0.05))
    ax_vio_tit.set_axis_off()
    ax_vio_tit.text(
    0.5, 0.5,
    'Within cluster distances: short vs long reads',
    ha='center', va='center',
    fontsize=18, fontweight='bold'
    )
    for ind,lab in enumerate(labels_set):
        d = [df.loc[lab,'dist_to_centr'] for df in dataframe_list]
        cur_col = ind%cols
        ax = fig.add_subplot(gs_vio[cur_row,cur_col])
        ax.violinplot(d)
        ax.set_title(lab)
        ax.set_xticks([1,2],labels=['short','long'])
        ax.set_ylabel('distance')
        if cur_col == cols-1 and cur_row < rows-1 and ind < len(labels_set)-1:
            cur_row += 1
            cur_col = 0
    dist_ma1 = file1['between']
    dist_ma2 = file2['between']
    all_dists = np.array([dist_ma1,dist_ma2]).flatten()
    p99 = np.percentile(all_dists,99)
    norm_md1 = dist_ma1/p99
    norm_md2 = dist_ma2/p99
    cur_row += 1
    cur_col=0
    gs_heat = gridspec.GridSpec(1,2,left=0.05,right=0.95,top=0.32,bottom=0.05)
    ax_heat_tit = fig.add_axes((0,0.33,1,0.05))
    ax_heat_tit.set_axis_off()
    ax_heat_tit.text(
        0.5,0.5,'Normalized between cluster distances',
        ha='center',va='center',fontsize=18,
        fontweight='bold'
    )
    for ind, ds in enumerate([norm_md1, norm_md2]):
        ax = fig.add_subplot(gs_heat[0, ind])
        cmap_rev = plt.get_cmap('cividis').reversed()
        im = ax.imshow(ds, cmap=cmap_rev,vmin=0,vmax=1)
        mode = ['Short', 'Long'][ind]
        ax.set_title(f'{mode} reads', fontsize=13, pad=10)
        ax.set_xticks(range(len(labels_set)), labels=labels_set, rotation=45,rotation_mode="anchor",ha="right")
        ax.set_yticks(range(len(labels_set)), labels=labels_set)
        ax.set_xlabel('Species')
        ax.set_ylabel('Species')
        cbar = plt.colorbar(im, ax=ax, label='Normalized Distance',shrink=0.8)
        cbar.set_label('Normalized distance',labelpad=8)
    plt.savefig(save_distance_visualization)
    
def main(args):
    file1 = np.load(args.file_1)
    file2 = np.load(args.file_2)
    dist1 = pd.DataFrame(file1['distances'],index=file1['true_label'],columns=['dist_to_centr'])
    dist2 = pd.DataFrame(file2['distances'],index=file2['true_label'],columns=['dist_to_centr'])
    nr_plots = len(set(file2['true_label']))
    rows,rows_violin,cols = nr_rows_cols(nr_plots)
    try_gs_vis(file1,file2,[dist1,dist2],rows,rows_violin,cols,args.result_png)

if __name__ == "__main__":
    args = argparse.Namespace(
        file_1 = "calculated_distances.npz",
        file_2 = "calculated_distances_2.npz",
        result_png = 'dist_vgl.png'
    )
    # parser = argparse.ArgumentParser(description='Calculate distances within and between clusters')
    # parser.add_argument('--file_1', type=str,default='data/short_reads/distances_short.npz', help='Path to the npz file for short reads generated by distances_within_between_cluster.py')
    # parser.add_argument('--file_2', type=str, default='data/long_reads/distances_long.npz', help='Path to the npz file for long reads generated by distances_within_between_cluster.py')
    # parser.add_argument('--result_png',type=str,default='calculated_distances.png',help='Path tp npz file to save calculated distances.png')
    # args = parser.parse_args()
    main(args)